# simple Cron job, airflow in prod
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ml-predict-job
spec:
  schedule: "0 2 * * *"  # Run daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: spark-predict
            image: ml-campaign-optimizer:latest
            command: ["python", "3_predict_job/predict_spark.py"]
            env:
            - name: CAMPAIGN_ID
              value: "1"
            - name: CONFIG_API_URL
              value: "http://config-api-service:8000"
          restartPolicy: OnFailure